# This GitHub workflow will automatically build and test code changes
name: Gradle build
on:
    push:
        paths:
            - '**.java'
            - build.gradle.kts
            - settings.gradle.kts
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Check out package
              uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: corretto
                java-version: 21
            - name: Run gradle build
              run: ./gradlew build
