# This GitHub workflow will automatically build and test code changes
name: Gradle build
on:
  # Run when pushing code or config changes to GitHub
  push:
    paths:
      - '**.java'
      - '**.yml'
      - build.gradle.kts
      - settings.gradle.kts
  # Run automatically for all pull requests
  pull_request:
  # Enable running workflow manually from GitHub Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out package
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Run gradle build
        run: gradle wrapper build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
